#!/usr/bin/dh-exec

debian/out/system/core/libbacktrace.so.*   usr/lib/${DEB_HOST_MULTIARCH}/android
debian/out/system/core/libbacktrace.so     usr/lib/${DEB_HOST_MULTIARCH}/android
debian/out/system/core/libcpu_features.so.* usr/lib/${DEB_HOST_MULTIARCH}/android
debian/out/system/core/libcpu_features.so  usr/lib/${DEB_HOST_MULTIARCH}/android
debian/out/system/core/liblzma.so.*        usr/lib/${DEB_HOST_MULTIARCH}/android
debian/out/system/core/liblzma.so          usr/lib/${DEB_HOST_MULTIARCH}/android
