#!/usr/bin/dh-exec

libnativehelper/include_jni/*          usr/include/android/nativehelper
libnativehelper/include/nativehelper   usr/include/android
libnativehelper/header_only_include/nativehelper usr/include/android
libnativehelper/libnativehelper.so     usr/lib/${DEB_HOST_MULTIARCH}/android
libnativehelper/platform_include/*     usr/include/android
libnativehelper/README                 usr/share/doc/android-libnativehelper
