#!/usr/bin/dh-exec

debian/include/external/libunwind/*.h    usr/include/android/lzma
external/libunwind/include/libunwind_i.h usr/include/android/unwind
external/libunwind/include/libunwind-*.h usr/include/android/unwind
external/libunwind/include/libunwind.h   usr/include/android/unwind
external/libunwind/include/unwind.h      usr/include/android/unwind
debian/out/external/libunwind/libunwind.so usr/lib/${DEB_HOST_MULTIARCH}/android
